### ISSUE TITLE
create a vertical prototype (implement a flutter app)

### ISSUE THREAD

**Issue by Kjani01** [mobileappdevhm19/HINT-Reader#12] opened 2019-04-24 11:10 UTC
In your Github repo create

    flutter app as vertical prototype

**Comment by ghost** [comment] 2019-04-26 11:49
## Features to implement
see https://github.com/mobileappdevhm19/apps4students-team-3/wiki/Design-Phase

### must have
*open page
*change font size w/ buttons
*dark mode

### if we have the time:
*rotation
*swiping between pages
*select book from our virtual bookshelf view to open it
*coloured sticky notes
*display position of page w/ scrollbar

### not to implement
* paragraph identifiers
* zooming with fingers
* table of contents
* popover fingers
* categories, folders, any form of hierarchical organisation

**Comment by GiorgioBullo** [comment] 2019-04-26 12:06
**Suggestion for a imageButton**:

Container(child: ConstrainedBox(
    constraints: BoxConstraints.expand(),
    child: FlatButton(onPressed: null,
        child: Image.asset('path/the_image.png'))))

**Comment by maxiking203** [comment] 2019-04-26 12:33
App has two Pages now BookshelView and BookView.
To get from the Main View (BookshelView ) to the BookView press the increment Button.
I will change the buttonstyle later with the above given solution.

**Comment by maxiking203** [comment] 2019-04-26 16:01
The button is changed now. Using a picture which is located in the "assets" direcotry.
To create the button I used the Suggestion from @GiorgioBullo and just changed Image.asset("assets/main_icon.png").
Not sure how we later could save our "pages" to make them the image of the button :D

**Comment by Kjani01** [comment] 2019-04-26 18:34
- Refactored Shel to Shel**f** :D 
- In our BookView, we now have two different images, depending on the orientation of the phone (portrait vs. landscape)
- There is now a button in the upper right with a little icon-sun. If your in normal mode, the sun is in black color. Press it, we get a reload and go into "darkmode". Here we currently have the image from the book shelf displayed in both orientations (so we can see we are in a different mode). If you press the now white sun in the upper right again, we get back into normal mode with the previous pictures

**Comment by GiorgioBullo** [comment] 2019-04-26 18:46
for the scrollbar, have a look to this:

https://medium.com/flutter-community/creating-draggable-scrollbar-in-flutter-a0ae8cf3143b

it is a very simple tutorial to create a customized scrollbar. The problem is that it is made with a scrollable list, and this could be different from what we want, because I guess that the pages of the book won't be a list... or maybe yes: a list of paragraph heheh

**Comment by maxiking203** [comment] 2019-04-26 20:46
Did the portrait view work on your phone?
Seems like in the current code version on github the app can't find the portrait picture because the file is named ".JPG" and not not like in code used ".jpg". Or is this only a issue on my device?

**Comment by maxiking203** [comment] 2019-04-27 10:03
Bug was fixed yesterday by @Kjani01!

**Comment by maxiking203** [comment] 2019-04-27 22:05
@wildeKaiserin implemented a prototype of the feature "change font size". Also the darkmode button was refactored by using the "setState()" function.

change font size:
For this feautre there are two buttons in the appbar. One to get a bigger font size and one for a smaller font sitze. If none of these two buttons are activated a "medium" front size will be shown.
The front size itself is implmented by a paramerter in the BookView and is needed to create a new BookView. The parameter is an int and should be assigned with the values -1 (big font) , 0 (medium font) or 1 (small font). 
Because we are not able to take real scrennshots from Tex we used some example pictures. Please be aware of the fact that currently there will be know changes when you chose the bigger oder smaller font and you try to activate the darkmode.
The smaller and bigger button are changig there color similar to the darkmode button when they are activated.

darkmode-button refactor:
Instead of creating a new BookView everytime the darkmode button was pressed, we now use the setState funcation to change the value of the darkmode parameter.


Maybe we should think about refactoring the orientation methode to be in a better Codestyle.

**Comment by maxiking203** [comment] 2019-04-30 19:07
Implemented Feautres for the Prototype:
- From "must have": open page, change font size, dark mode
- From "if we have the time": rotation

We implemented all features that we called as "must have" and additionally we implemented the rotation feature. In summary we reached our Goal! Good job team, great work!

There is only on "bug" left. If the orientation of the device gets changed the state of the BookView-Page will be reseted, so the default settings for darkmode and fontsize are chosen. Trying to fix this till friday, but I am not sure if we find a solution that fast.

@mobileappdevhm19/team-3 Please confirm that the named features are implemented, thanks!

Screenshots will be in the gh-pages branch soon.

**Comment by maxiking203** [comment] 2019-04-30 20:02
The bug is fixed now :-D 
The State now only gets reseted if you leave a BookView-Page. 
Fixed it by adding the darkmode and size paramerter to CookViewState, so it's not only in the BookViewPage.

**Comment by ghost** [comment] 2019-05-02 09:47
review: all required functionality found, i'm happy with it.
using pictures is fine for simulating the backend.

maybe add the screenshots to the wiki when you have the time.

**Comment by Kjani01** [comment] 2019-05-02 10:02
Review: All requirements are there and it looks very good. 
Orientation, darkmode, size, everythings there

**Comment by maxiking203** [comment] 2019-05-02 14:54
I think two Reviewer a engouh. As I can see both confirmed the implemented functionalitys.
I added the Screenshots to the Wiki.
This Issue is Done!

**Closed as completed by maxiking203** 2019-05-02 14:54 UTC
